# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-08 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gold', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='goldDiggers',
            new_name='goldDigger',
        ),
    ]
